/**
 * Maritime Cloud Service Registry API
 * Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
 *
 * OpenAPI spec version: 0.9
 * Contact: josef.jahn@frequentis.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Doc } from './doc';
import { Specification } from './specification';
import { SpecificationTemplate } from './specificationTemplate';
import { Xml } from './xml';


/**
 * Holds a description of a technical design.A design can be compatible to one or morespecification templates.It has at least a technical representation of thedescriptiion in form of an XML and a filled out templateas e.g. word document.
 */
export interface Design { 
    comment?: string;
    designAsDoc?: Doc;
    designAsXml?: Xml;
    designId?: string;
    docs?: Array<Doc>;
    id?: number;
    implementedSpecificationVersion?: SpecificationTemplate;
    lastUpdatedAt?: string;
    name?: string;
    organizationId?: string;
    publishedAt?: string;
    specifications?: Array<Specification>;
    status?: string;
    version?: string;
}
