/**
 * Maritime Cloud Service Registry API
 * Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
 *
 * OpenAPI spec version: 0.9
 * Contact: josef.jahn@frequentis.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Doc } from './doc';
import { JsonNode } from './jsonNode';
import { SpecificationTemplate } from './specificationTemplate';
import { Xml } from './xml';


/**
 * Holds a description of an service instance.An instance can be compatible to one or more specification templates. It has at least a technical representation of thedescriptiion in form of an XML and a filled out templateas e.g. word document.
 */
export interface Instance { 
    comment?: string;
    compliant?: boolean;
    designId?: string;
    docs?: Array<Doc>;
    endpointType?: string;
    endpointUri?: string;
    geometry?: JsonNode;
    geometryContentType?: string;
    id?: number;
    imo?: string;
    implementedSpecificationVersion?: SpecificationTemplate;
    instanceAsDoc?: Doc;
    instanceAsXml?: Xml;
    instanceId?: string;
    keywords?: string;
    lastUpdatedAt?: string;
    mmsi?: string;
    name?: string;
    organizationId?: string;
    publishedAt?: string;
    serviceType?: string;
    specificationId?: string;
    status?: string;
    unlocode?: string;
    version?: string;
}
