/**
 * Maritime Cloud Service Registry API
 * Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
 *
 * OpenAPI spec version: 0.9
 * Contact: josef.jahn@frequentis.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface JsonNode { 
    array?: boolean;
    bigDecimal?: boolean;
    bigInteger?: boolean;
    binary?: boolean;
    _boolean?: boolean;
    containerNode?: boolean;
    _double?: boolean;
    _float?: boolean;
    floatingPointNumber?: boolean;
    _int?: boolean;
    integralNumber?: boolean;
    _long?: boolean;
    missingNode?: boolean;
    nodeType?: JsonNode.NodeTypeEnum;
    _null?: boolean;
    number?: boolean;
    object?: boolean;
    pojo?: boolean;
    _short?: boolean;
    textual?: boolean;
    valueNode?: boolean;
}
export namespace JsonNode {
    export type NodeTypeEnum = 'ARRAY' | 'BINARY' | 'BOOLEAN' | 'MISSING' | 'NULL' | 'NUMBER' | 'OBJECT' | 'POJO' | 'STRING';
    export const NodeTypeEnum = {
        ARRAY: 'ARRAY' as NodeTypeEnum,
        BINARY: 'BINARY' as NodeTypeEnum,
        BOOLEAN: 'BOOLEAN' as NodeTypeEnum,
        MISSING: 'MISSING' as NodeTypeEnum,
        NULL: 'NULL' as NodeTypeEnum,
        NUMBER: 'NUMBER' as NodeTypeEnum,
        OBJECT: 'OBJECT' as NodeTypeEnum,
        POJO: 'POJO' as NodeTypeEnum,
        STRING: 'STRING' as NodeTypeEnum
    };
}
