/**
 * Maritime Connectivity Platform Service Registry API
 * Maritime Connectivity Platform Service Registry, developed by the MCC MSR WG
 *
 * OpenAPI spec version: 0.1
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LedgerRequestDto { 
    createdAt?: string;
    id?: number;
    lastUpdatedAt?: string;
    reason?: string;
    serviceInstanceId: number;
    status?: LedgerRequestDto.StatusEnum;
}
export namespace LedgerRequestDto {
    export type StatusEnum = 'CREATED' | 'FAILED' | 'INACTIVE' | 'REJECTED' | 'REQUESTING' | 'SUCCEEDED' | 'VETTED' | 'VETTING';
    export const StatusEnum = {
        CREATED: 'CREATED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum,
        INACTIVE: 'INACTIVE' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum,
        REQUESTING: 'REQUESTING' as StatusEnum,
        SUCCEEDED: 'SUCCEEDED' as StatusEnum,
        VETTED: 'VETTED' as StatusEnum,
        VETTING: 'VETTING' as StatusEnum
    };
}
