/**
 * Maritime Cloud Service Registry API
 * Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
 *
 * OpenAPI spec version: 0.9
 * Contact: josef.jahn@frequentis.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Doc } from './doc';
import { Xsd } from './xsd';


/**
 * A SpecificationTemplate contains information on how to define a aspects ofa service.It has a type do differentiate between e.g. logical definitions andconcrete service instances.Templates will evolve, that's why they have a version.
 */
export interface SpecificationTemplate { 
    comment?: string;
    docs?: Array<Doc>;
    guidelineDoc?: Doc;
    id?: number;
    name?: string;
    templateDoc?: Doc;
    type?: SpecificationTemplate.TypeEnum;
    version?: string;
    xsds?: Array<Xsd>;
}
export namespace SpecificationTemplate {
    export type TypeEnum = 'SPECIFICATION' | 'DESIGN' | 'INSTANCE';
    export const TypeEnum = {
        SPECIFICATION: 'SPECIFICATION' as TypeEnum,
        DESIGN: 'DESIGN' as TypeEnum,
        INSTANCE: 'INSTANCE' as TypeEnum
    };
}
