/**
 * Maritime Connectivity Platform Service Registry API
 * Maritime Connectivity Platform Service Registry, developed by the MCC MSR WG
 *
 * OpenAPI spec version: 0.1
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { XmlDto } from '../model/xmlDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class XmlControllerService {

    protected basePath = 'https://msr-test.maritimeconnectivity.net';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createXml
     * 
     * @param xmlDto xmlDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createXmlUsingPOST(xmlDto: XmlDto, observe?: 'body', reportProgress?: boolean): Observable<XmlDto>;
    public createXmlUsingPOST(xmlDto: XmlDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<XmlDto>>;
    public createXmlUsingPOST(xmlDto: XmlDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<XmlDto>>;
    public createXmlUsingPOST(xmlDto: XmlDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (xmlDto === null || xmlDto === undefined) {
            throw new Error('Required parameter xmlDto was null or undefined when calling createXmlUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<XmlDto>(`${this.basePath}/api/xmls`,
            xmlDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteXml
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteXmlUsingDELETE(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteXmlUsingDELETE(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteXmlUsingDELETE(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteXmlUsingDELETE(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteXmlUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/xmls/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllXmls
     * 
     * @param offset 
     * @param paged 
     * @param pageNumber 
     * @param pageSize 
     * @param sortSorted 
     * @param sortUnsorted 
     * @param unpaged 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllXmlsUsingGET(offset?: number, paged?: boolean, pageNumber?: number, pageSize?: number, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<XmlDto>>;
    public getAllXmlsUsingGET(offset?: number, paged?: boolean, pageNumber?: number, pageSize?: number, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<XmlDto>>>;
    public getAllXmlsUsingGET(offset?: number, paged?: boolean, pageNumber?: number, pageSize?: number, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<XmlDto>>>;
    public getAllXmlsUsingGET(offset?: number, paged?: boolean, pageNumber?: number, pageSize?: number, sortSorted?: boolean, sortUnsorted?: boolean, unpaged?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {








        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (paged !== undefined && paged !== null) {
            queryParameters = queryParameters.set('paged', <any>paged);
        }
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (sortSorted !== undefined && sortSorted !== null) {
            queryParameters = queryParameters.set('sort.sorted', <any>sortSorted);
        }
        if (sortUnsorted !== undefined && sortUnsorted !== null) {
            queryParameters = queryParameters.set('sort.unsorted', <any>sortUnsorted);
        }
        if (unpaged !== undefined && unpaged !== null) {
            queryParameters = queryParameters.set('unpaged', <any>unpaged);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<XmlDto>>(`${this.basePath}/api/xmls`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getG1128Schema
     * 
     * @param schema schema
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getG1128SchemaUsingGET(schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe?: 'body', reportProgress?: boolean): Observable<string>;
    public getG1128SchemaUsingGET(schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public getG1128SchemaUsingGET(schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public getG1128SchemaUsingGET(schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (schema === null || schema === undefined) {
            throw new Error('Required parameter schema was null or undefined when calling getG1128SchemaUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/api/xmls/schemas/${encodeURIComponent(String(schema))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getXml
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getXmlUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<XmlDto>;
    public getXmlUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<XmlDto>>;
    public getXmlUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<XmlDto>>;
    public getXmlUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getXmlUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<XmlDto>(`${this.basePath}/api/xmls/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateXml
     * 
     * @param id id
     * @param xmlDto xmlDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateXmlUsingPUT(id: number, xmlDto: XmlDto, observe?: 'body', reportProgress?: boolean): Observable<XmlDto>;
    public updateXmlUsingPUT(id: number, xmlDto: XmlDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<XmlDto>>;
    public updateXmlUsingPUT(id: number, xmlDto: XmlDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<XmlDto>>;
    public updateXmlUsingPUT(id: number, xmlDto: XmlDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateXmlUsingPUT.');
        }

        if (xmlDto === null || xmlDto === undefined) {
            throw new Error('Required parameter xmlDto was null or undefined when calling updateXmlUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<XmlDto>(`${this.basePath}/api/xmls/${encodeURIComponent(String(id))}`,
            xmlDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * validateXmlWithG1128Schema
     * 
     * @param content content
     * @param schema schema
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public validateXmlWithG1128SchemaUsingPOST(content: string, schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public validateXmlWithG1128SchemaUsingPOST(content: string, schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public validateXmlWithG1128SchemaUsingPOST(content: string, schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public validateXmlWithG1128SchemaUsingPOST(content: string, schema: 'BASE' | 'DESIGN' | 'INSTANCE' | 'SERVICE', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (content === null || content === undefined) {
            throw new Error('Required parameter content was null or undefined when calling validateXmlWithG1128SchemaUsingPOST.');
        }

        if (schema === null || schema === undefined) {
            throw new Error('Required parameter schema was null or undefined when calling validateXmlWithG1128SchemaUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/xml'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/xmls/validate/${encodeURIComponent(String(schema))}`,
            content,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
