/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.
 *
 * OpenAPI spec version: 0.12.2
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Certificate { 
    /**
     * The certificate on PEM format
     */
    certificate?: string;
    createdAt?: Date;
    end?: Date;
    id?: number;
    revokeReason?: string;
    revoked?: boolean;
    revokedAt?: Date;
    serialNumber?: string;
    start?: Date;
    updatedAt?: Date;
}
