/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.
 *
 * OpenAPI spec version: 0.12.2
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IdentityProviderAttribute { 
    /**
     * OpenId Connect or SAML2 attribute name
     */
    attributeName: IdentityProviderAttribute.AttributeNameEnum;
    /**
     * OpenId Connect or SAML2 attribute value
     */
    attributeValue: string;
    createdAt?: Date;
    updatedAt?: Date;
}
export namespace IdentityProviderAttribute {
    export type AttributeNameEnum = 'authorizationUrl' | 'clientId' | 'clientSecret' | 'emailAttr' | 'firstNameAttr' | 'importUrl' | 'issuer' | 'lastNameAttr' | 'logoutUrl' | 'permissionsAttr' | 'postBindingAuthnRequest' | 'postBindingResponse' | 'providerType' | 'publicKeySignatureVerifier' | 'signingCertificate' | 'singleLogoutServiceUrl' | 'singleSignOnServiceUrl' | 'tokenUrl' | 'userInfoUrl' | 'usernameAttr' | 'validateSignature' | 'wantAuthnRequestsSigned';
    export const AttributeNameEnum = {
        AuthorizationUrl: 'authorizationUrl' as AttributeNameEnum,
        ClientId: 'clientId' as AttributeNameEnum,
        ClientSecret: 'clientSecret' as AttributeNameEnum,
        EmailAttr: 'emailAttr' as AttributeNameEnum,
        FirstNameAttr: 'firstNameAttr' as AttributeNameEnum,
        ImportUrl: 'importUrl' as AttributeNameEnum,
        Issuer: 'issuer' as AttributeNameEnum,
        LastNameAttr: 'lastNameAttr' as AttributeNameEnum,
        LogoutUrl: 'logoutUrl' as AttributeNameEnum,
        PermissionsAttr: 'permissionsAttr' as AttributeNameEnum,
        PostBindingAuthnRequest: 'postBindingAuthnRequest' as AttributeNameEnum,
        PostBindingResponse: 'postBindingResponse' as AttributeNameEnum,
        ProviderType: 'providerType' as AttributeNameEnum,
        PublicKeySignatureVerifier: 'publicKeySignatureVerifier' as AttributeNameEnum,
        SigningCertificate: 'signingCertificate' as AttributeNameEnum,
        SingleLogoutServiceUrl: 'singleLogoutServiceUrl' as AttributeNameEnum,
        SingleSignOnServiceUrl: 'singleSignOnServiceUrl' as AttributeNameEnum,
        TokenUrl: 'tokenUrl' as AttributeNameEnum,
        UserInfoUrl: 'userInfoUrl' as AttributeNameEnum,
        UsernameAttr: 'usernameAttr' as AttributeNameEnum,
        ValidateSignature: 'validateSignature' as AttributeNameEnum,
        WantAuthnRequestsSigned: 'wantAuthnRequestsSigned' as AttributeNameEnum
    };
}
