/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.
 *
 * OpenAPI spec version: 0.12.2
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Certificate } from './certificate';
import { IdentityProviderAttribute } from './identityProviderAttribute';


export interface Organization { 
    address: string;
    /**
     * Cannot be created/updated by editing in the model. Use the dedicate create and revoke calls.
     */
    certificates?: Array<Certificate>;
    country: string;
    createdAt?: Date;
    email: string;
    /**
     * Type of identity federation used by organization
     */
    federationType?: Organization.FederationTypeEnum;
    /**
     * URL of MMS that the identity is registered
     */
    homeMMSUrl?: string;
    id?: number;
    identityProviderAttributes?: Array<IdentityProviderAttribute>;
    /**
     * Maritime Connectivity Platform Maritime Resource Name
     */
    mrn: string;
    /**
     * Subsidiary Maritime Resource Name
     */
    mrnSubsidiary?: string;
    /**
     * The name of the organization
     */
    name: string;
    updatedAt?: Date;
    url: string;
}
export namespace Organization {
    export type FederationTypeEnum = 'external-idp' | 'own-idp' | 'test-idp';
    export const FederationTypeEnum = {
        ExternalIdp: 'external-idp' as FederationTypeEnum,
        OwnIdp: 'own-idp' as FederationTypeEnum,
        TestIdp: 'test-idp' as FederationTypeEnum
    };
}
