/**
 * Maritime Connectivity Platform Identity Registry API
 * The MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.
 *
 * OpenAPI spec version: 0.12.2
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Role { 
    createdAt?: Date;
    id?: number;
    idOrganization?: number;
    /**
     * The permission that should be mapped to the role
     */
    permission: string;
    /**
     * The role that should be mapped to the permission
     */
    roleName: Role.RoleNameEnum;
    updatedAt?: Date;
}
export namespace Role {
    export type RoleNameEnum = 'ROLE_APPROVE_ORG' | 'ROLE_DEVICE_ADMIN' | 'ROLE_ENTITY_ADMIN' | 'ROLE_MMS_ADMIN' | 'ROLE_ORG_ADMIN' | 'ROLE_SERVICE_ADMIN' | 'ROLE_SITE_ADMIN' | 'ROLE_USER' | 'ROLE_USER_ADMIN' | 'ROLE_VESSEL_ADMIN';
    export const RoleNameEnum = {
        APPROVEORG: 'ROLE_APPROVE_ORG' as RoleNameEnum,
        DEVICEADMIN: 'ROLE_DEVICE_ADMIN' as RoleNameEnum,
        ENTITYADMIN: 'ROLE_ENTITY_ADMIN' as RoleNameEnum,
        MMSADMIN: 'ROLE_MMS_ADMIN' as RoleNameEnum,
        ORGADMIN: 'ROLE_ORG_ADMIN' as RoleNameEnum,
        SERVICEADMIN: 'ROLE_SERVICE_ADMIN' as RoleNameEnum,
        SITEADMIN: 'ROLE_SITE_ADMIN' as RoleNameEnum,
        USER: 'ROLE_USER' as RoleNameEnum,
        USERADMIN: 'ROLE_USER_ADMIN' as RoleNameEnum,
        VESSELADMIN: 'ROLE_VESSEL_ADMIN' as RoleNameEnum
    };
}
